%YAML 1.2
---
# Sensor Type: 0: IMU; 1: Non-depth Camera; 2: Depth Camera; 3: LiDAR
sensor_type: 1
image_width: 612
image_height: 514

# Sensing Modality: 0: RGB; 1: thermal
sensing_modality: 0

# Optional mask
mask: ./masks/rgb_1_mask.png

# Lens Normal Map, use npz for best precision
lens_normal_map: ./lens_normal_maps/rgb_1_lens_normal_map.npy

# Intrinsic
intrinsic:
    # Camera Model Type: 0: Pinhole; 1: Mei (Fisheye)
    model_type: 1
    mirror_parameters:
        xi: 1.8984139573834302
    distortion_parameters: # radial-tangential distortion
        k1: -0.06295484286575274
        k2: 0.2433102678231446
        p1: 0.0007678138486198439
        p2: -0.0008818463106141355
    projection_parameters:
        gamma1: 426.45112572
        gamma2: 426.340563664
        u0: 302.640717308
        v0: 253.528397601
